version: '3.1'
services:
  #https://prometheus.io/docs/prometheus/latest/installation
  #  prometheus:
  #  image: prom/prometheus
  #  ports:
  #    - "9090:9090"
  #  volumes:
  #    - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
  #  command:
  #    - '--config.file=/etc/prometheus/prometheus.yaml'
  
  #https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/
  grafana: 
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    environment:
       DATABASE_HOST: host.docker.internal
       DATABASE_PORT: 3306
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/grafana.db:/var/lib/grafana/grafana.db
