version: '3.1'
services:
  spring_app:
    build:
      context: ./java-api
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - network.interface=Wi-Fi
    volumes:
      - ./java-api/target:/app
    entrypoint: ["java", "-jar", "/app/ipheatmap-0.0.1-SNAPSHOT.jar"]

  #https://prometheus.io/docs/prometheus/latest/installation
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  
  #https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/
  #graphana: 
  #  image: grafana/grafana-oss
  #  ports:
  #    - "3000:3000"
  #  volumes:
  #    - ./grafana/provisioning:/etc/grafana/provisioning